<?php

namespace Ups\Entity\Pickup;

use Ups\Entity\SerializableEntity;

class PickupCancelRequest extends SerializableEntity
{

    /**
     * Cancel pickup by Pickup Request Number (PRN). Valid values:
     * - accountnumber 
     * - prn
     * @var string
     */
    private $CancelBy;

    /**
     * The pickup request number (PRN) generated by UPS pickup system.
     * Required if CancelBy = prn
     * @var string
     */
    private $PRN;

    /**
     * Set - prn
     *
     * @param  string  $CancelBy  - prn
     *
     * @return  self
     */ 
    public function setCancelBy(string $CancelBy)
    {
        $this->CancelBy = $CancelBy;

        return $this;
    }

    /**
     * Set required if CancelBy = prn
     *
     * @param  string  $PRN  Required if CancelBy = prn
     *
     * @return  self
     */ 
    public function setPRN(string $PRN)
    {
        $this->PRN = $PRN;

        return $this;
    }

    /**
     * Get - prn
     *
     * @return  string
     */ 
    public function getCancelBy()
    {
        return $this->CancelBy;
    }

    /**
     * Get required if CancelBy = prn
     *
     * @return  string
     */ 
    public function getPRN()
    {
        return $this->PRN;
    }
}
